plugins:
  - jekyll-multiple-languages-plugin
languages: ["en", "cn"]
languageNames:
  cn: Chinese
  en: English
defaultLang: en
exclude_from_localizations: ["javascript", "images", "css"]

theme: jekyll-theme-architect
title: Richmond Hill Yellow Page
description: Serve Richmond Hill neibourhood
url: https://garfieldtony.github.io/RichmondHill/
