theme: jekyll-theme-architect
title: Richmond Hill Yellow Page
description: Serve Richmond Hill neibourhood
url: https://garfieldtony.github.io/RichmondHill/
languages: ["en", "cn"]
exclude_from_localizations: ["images"]
defaultLang: en
languageNames:
  cn: Chinese
  en: English
